- name: create ec2 and route53 records
  hosts: localhost
  vars:
    zone: daws.info
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-traffic #replace with your aws value
      image_id: ami-0220d79f3f480ecf5
      tags:
        Name: "{{ item }}"

    loop:  "{{ instances }}"
    register: ec2_instance_info


  - name: print output
    ansible.builtin.debug:
      msg: "output: {{ ec2_instance_info }}"

  - name: create route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: " {{ item.tags.Name }}.{{ zone }} "
      type: A
      value: "{{ item.private_ip_address }}"
      overwrite: true
      ttl: 1
    loop: "{{ all_instances }}"
    

    

